version: '3.7'

services:

  sample:
    container_name: calculator-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "42051:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true